# API Configuration
base.url=https://reqres.in
api.version=/api
api.key=free_user_3GJRz7IruA5c4eRCkkRTDO1DLrF

# Authentication
auth.email=eve.holt@reqres.in
auth.password=cityslicka

# Timeouts
connection.timeout=10000
read.timeout=10000